In [5]:
!pip3 install mysql-connector

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector in /home/vimal/.local/lib/python3.10/site-packages (2.2.9)

In [1]:
import mysql.connector

In [2]:
connection = mysql.connector.connect(
        host="localhost",
        user="root",
        password="",
        database="ICT_EMPLOYEE"
    )

In [3]:
def create_employee():
    cursor = connection.cursor()
    name = input("Enter employee name: ")
    department = input("Enter department: ")
    salary = float(input("Enter salary: "))
    query = "INSERT INTO employees (name, department, salary) VALUES (%s, %s, %s)"
    values = (name, department, salary)
    cursor.execute(query, values)
    connection.commit()

In [4]:
def delete_employee():
    cursor = connection.cursor()
    employee_id = int(input("Enter employee ID to delete: "))
    query = "SELECT * FROM employees WHERE id = %s"
    values = (employee_id,)
    cursor.execute(query, values)
    result = cursor.fetchone()
    if result is None:
        print("Employee not found!")
    else:
        query = "DELETE FROM employees WHERE id = %s"
        cursor.execute(query, values)
        connection.commit()
        print("Employee deleted successfully!")
        cursor.close()

In [5]:
def list_employees():
    cursor = connection.cursor()
    query = "SELECT * FROM employees"
    cursor.execute(query)
    employees = cursor.fetchall()
    if employees:
        for employee in employees:
            print("ID: {}, Name: {}, Department: {}, Salary: {}".format(employee[0], employee[1], employee[2], employee[3]))
    else:
        print("No employees found!")

    cursor.close()

In [6]:
def update_employee():
    cursor = connection.cursor()
    employee_id = int(input("Enter employee ID to update: "))
    query = "SELECT * FROM employees WHERE id = %s"
    values = (employee_id,)
    cursor.execute(query, values)
    result = cursor.fetchone()
    if result is None:
        print("Employee not found!")
    else:
        name = input("Enter new name (leave blank to skip): ")
        department = input("Enter new department (leave blank to skip): ")
        salary = input("Enter new salary (leave blank to skip): ")
        query = "UPDATE employees SET "
        update_values = []

        if name:
            query += "name = %s, "
            update_values.append(name)
        if department:
            query += "department = %s, "
            update_values.append(department)
        if salary:
            query += "salary = %s, "
            update_values.append(float(salary))
        query = query[:-2]
        query += " WHERE id = %s"
        update_values.append(employee_id)
        cursor.execute(query, tuple(update_values))
        connection.commit()

        print("Employee updated successfully!")

    cursor.close()

In [7]:
def sort_details():
    cursor = connection.cursor()

    print("List of Employees:")

    sort_option = input("Sort by (D)epartment, (S)alary, or (N)one: ")
    if sort_option.upper() == "D":
        query = "SELECT * FROM employees ORDER BY department"
    elif sort_option.upper() == "S":
        query = "SELECT * FROM employees ORDER BY salary"
    else:
        query = "SELECT * FROM employees"

    cursor.execute(query)
    employees = cursor.fetchall()

    if employees:
        for employee in employees:
            print("ID: {}, Name: {}, Department: {}, Salary: {}".format(employee[0], employee[1], employee[2], employee[3]))
    else:
        print("No employees found!")

    cursor.close()

In [8]:
def filler_details():
    cursor = connection.cursor()

    print("List of Employees:")

    filter_option = input("Filter by (D)epartment, (S)alary, or (N)ame: ")
    filter_keyword= input("Enter the keyword to filter")
    if filter_option.upper() == 'N':
        query = "SELECT * FROM employees WHERE name LIKE '%{}%'".format(filter_keyword)
    elif filter_option.upper() == "D":
        query = "SELECT * FROM employees WHERE department LIKE '%{}%'".format(filter_keyword)
    elif filter_option.upper() == "S":
        query = "SELECT * FROM employees WHERE salary LIKE '%{}%'".format(filter_keyword)
    else:
        query = "SELECT * FROM employees"

    cursor.execute(query)
    employees = cursor.fetchall()

    if employees:
        for employee in employees:
            print("ID: {}, Name: {}, Department: {}, Salary: {}".format(employee[0], employee[1], employee[2], employee[3]))
    else:
        print("No employees found!")

    cursor.close()

In [9]:
if __name__ == "__main__":
     while True:
        print("\nEmployee Management System")
        print("1. Create new employee")
        print("2. Update existing employee")
        print("3. Delete employee")
        print("4. List all employees")
        print("5. Filter details")
        print("6. Sort details")
        print("7. Exit")

        choice = input("Enter your choice: ")

        if choice == "1":
            create_employee()
        elif choice == "2":
            update_employee()
        elif choice == "3":
            delete_employee()
        elif choice == "4":
            list_employees()
        elif choice == "5":
            filler_details()
        elif choice == "6":
            sort_details()
        elif choice == "7":
            break
        else:
            connection.close()
            print("Invalid choice. Please try again.")

Employee Management System
1. Create new employee
2. Update existing employee
3. Delete employee
4. List all employees
5. Filter details
6. Sort details
7. Exit
Enter your choice: 4
ID: 1, Name: Sharan, Department: Python, Salary: 10000.00
ID: 3, Name: AMAL, Department: AI, Salary: 12000.00
ID: 4, Name: abin, Department: Python, Salary: 15000.00
ID: 5, Name: Rahul, Department: Android, Salary: 20000.00

Employee Management System
1. Create new employee
2. Update existing employee
3. Delete employee
4. List all employees
5. Filter details
6. Sort details
7. Exit
Enter your choice: 1
Enter employee name: aswin
Enter department: Java
Enter salary: 25000

Employee Management System
1. Create new employee
2. Update existing employee
3. Delete employee
4. List all employees
5. Filter details
6. Sort details
7. Exit
Enter your choice: 4
ID: 1, Name: Sharan, Department: Python, Salary: 10000.00
ID: 3, Name: AMAL, Department: AI, Salary: 12000.00
ID: 4, Name: abin, Department: Python, Salary: 15000.00
ID: 5, Name: Rahul, Department: Android, Salary: 20000.00
ID: 6, Name: aswin, Department: Java, Salary: 25000.00

Employee Management System
1. Create new employee
2. Update existing employee
3. Delete employee
4. List all employees
5. Filter details
6. Sort details
7. Exit
Enter your choice: 2
Enter employee ID to update: 6
Enter new name (leave blank to skip):
Enter new department (leave blank to skip):
Enter new salary (leave blank to skip): 15000
Employee updated successfully!

Employee Management System
1. Create new employee
2. Update existing employee
3. Delete employee
4. List all employees
5. Filter details
6. Sort details
7. Exit
Enter your choice: 3
Enter employee ID to delete: 1
Employee deleted successfully!

Employee Management System
1. Create new employee
2. Update existing employee
3. Delete employee
4. List all employees
5. Filter details
6. Sort details
7. Exit
Enter your choice: 4
ID: 3, Name: AMAL, Department: AI, Salary: 12000.00
ID: 4, Name: abin, Department: Python, Salary: 15000.00
ID: 5, Name: Rahul, Department: Android, Salary: 20000.00
ID: 6, Name: aswin, Department: Java, Salary: 15000.00

Employee Management System
1. Create new employee
2. Update existing employee
3. Delete employee
4. List all employees
5. Filter details
6. Sort details
7. Exit
Enter your choice: 5
List of Employees:
Filter by (D)epartment, (S)alary, or (N)ame: N
Enter the keyword to filterin
ID: 4, Name: abin, Department: Python, Salary: 15000.00
ID: 6, Name: aswin, Department: Java, Salary: 15000.00

Employee Management System
1. Create new employee
2. Update existing employee
3. Delete employee
4. List all employees
5. Filter details
6. Sort details
7. Exit
Enter your choice: 6
List of Employees:
Sort by (D)epartment, (S)alary, or (N)one: S
ID: 3, Name: AMAL, Department: AI, Salary: 12000.00
ID: 4, Name: abin, Department: Python, Salary: 15000.00
ID: 6, Name: aswin, Department: Java, Salary: 15000.00
ID: 5, Name: Rahul, Department: Android, Salary: 20000.00

Employee Management System
1. Create new employee
2. Update existing employee
3. Delete employee
4. List all employees
5. Filter details
6. Sort details
7. Exit
Enter your choice: 7